**Lab 1-2 : Graph Representation**
- Instuctor : Kijung Shin
- Teaching Assistants : Deukryeol Yoon(main), Hyunju Lee, Shinhwan Kang 
- 본 실습에서는 그래프를 표현할 수 있는 다양한 방법에 대해서 알아본다.


In [8]:
import sys
import numpy as np)
np.set_printoptions(threshold=sys.maxsize)

SyntaxError: invalid syntax (<ipython-input-8-a1d284b79aa4>, line 2)

In [6]:
import networkx as nx
import os                                   
import os.path as osp                       
import numpy as np
importdrive
G = nx.Graph()
DiGraph = nx.DiGraph()

NameError: name 'importdrive' is not defined

In [9]:
# 10개의 node로 이루어진, 원 모양의 그래프 정보를 가져옵니다.
# 각 데이터셋은 edge 형태로 저장되어 있습니다.
print("###### Read Graphs ######")
data = osp.abspath(osp.join(os.getcwd(), '/content/drive/MyDrive/boostcamp/data/graph/lab/lab1/small_cycle.txt'))

data

###### Read Graphs ######


'/content/drive/MyDrive/boostcamp/data/graph/lab/lab1/small_cycle.txt'

In [15]:
f = open(data)
for line in f:                                                               # 파일의 각 라인은 v1 v2 형태로 저장되어있습니다.
	v1, v2 = list(map(int, line.split()))                                      # 각 라인을 읽어 space를 기준으로 split해주고 이를 integer mapping해줍니다.
	G.add_edge(v1, v2)

print(G.edges)

[(1, 2), (1, 10), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)]


In [16]:
# 그래프를 인접 리스트로 저장
print("###### Graph to List ######")                                     
ListGraph = nx.to_dict_of_lists(G)
for v in DiGraph:
    print(str(v) + " : " + str(ListGraph[v]))

###### Graph to List ######


In [19]:
ListGraph

{1: [2, 10],
 2: [1, 3],
 3: [2, 4],
 4: [3, 5],
 5: [4, 6],
 6: [5, 7],
 7: [6, 8],
 8: [7, 9],
 9: [8, 10],
 10: [9, 1]}

In [ ]:
# 그래프를 간선 리스트로 저장
print("###### Graph to EdgeList ######")                                  
EdgeListGraph = nx.to_edgelist(G)                                     
for e in EdgeListGraph:
    v1, v2, w = e
    print(v1, v2)

###### Graph to EdgeList ######
[(1, 2, {}), (1, 10, {}), (2, 3, {}), (3, 4, {}), (4, 5, {}), (5, 6, {}), (6, 7, {}), (7, 8, {}), (8, 9, {}), (9, 10, {})]
1 2
1 10
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10


In [ ]:
# 그래프를 인접 행렬(일반 행렬)로 저장
print("###### Graph to numpy array ######")
NumpyArrayGraph = nx.to_numpy_array(G)                                    
print(NumpyArrayGraph)


###### Graph to numpy array ######
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [ ]:
# 그래프를 인접 행렬(희소 행렬)로 저장
print("###### Graph to Spicy sparse matrix ######")
SparseMatrixGraph = nx.to_scipy_sparse_matrix(G)                       
print(SparseMatrixGraph)

###### Graph to Spicy sparse matrix ######
  (0, 1)	1
  (0, 9)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 3)	1
  (3, 2)	1
  (3, 4)	1
  (4, 3)	1
  (4, 5)	1
  (5, 4)	1
  (5, 6)	1
  (6, 5)	1
  (6, 7)	1
  (7, 6)	1
  (7, 8)	1
  (8, 7)	1
  (8, 9)	1
  (9, 0)	1
  (9, 8)	1
