**Lab 1-2 : Graph Representation**
- Instuctor : Kijung Shin
- Teaching Assistants : Deukryeol Yoon(main), Hyunju Lee, Shinhwan Kang 
- 본 실습에서는 그래프를 표현할 수 있는 다양한 방법에 대해서 알아본다.


In [1]:
import sys
import numpy as np
np.set_printoptions(threshold=sys.maxsize)

In [20]:
import networkx as nx
import os                                   
import os.path as osp                       
import numpy as rive
G = nx.Graph()
DiGraph = nx.DiGraph()

In [5]:
G, DiGraph

(<networkx.classes.graph.Graph at 0x7ff9e4185e50>,
 <networkx.classes.digraph.DiGraph at 0x7ff9e4185cd0>)

In [27]:
G.nodes

NodeView(())

In [28]:
# 10개의 node로 이루어진, 원 모양의 그래프 정보를 가져옵니다.
# 각 데이터셋은 edge 형태로 저장되어 있습니다.

print("###### Read Graphs ######")
PATH = os.path.join('graph', 'lab', 'lab1', 'small_cycle.txt')

###### Read Graphs ######


In [66]:
f = open(PATH)
for line in f:                                                               # 파일의 각 라인은 v1 v2 형태로 저장되어있습니다.
	v1, v2 = list(map(int, line.split()))                                      # 각 라인을 읽어 space를 기준으로 split해주고 이를 integer mapping해줍니다.
	G.add_edge(v1, v2)

print(G.edges)

[(1, 10), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)]


In [30]:
# 그래프를 인접 리스트로 저장
print("###### Graph to List ######")                                     
ListGraph = nx.to_dict_of_lists(G)
for v in DiGraph:
    print(str(v) + " : " + str(ListGraph[v]))

###### Graph to List ######


In [31]:
ListGraph

{1: [2, 10],
 2: [1, 3],
 3: [2, 4],
 4: [3, 5],
 5: [4, 6],
 6: [5, 7],
 7: [6, 8],
 8: [7, 9],
 9: [8, 10],
 10: [9, 1]}

In [32]:
# 그래프를 간선 리스트로 저장
print("###### Graph to EdgeList ######")                                  
EdgeListGraph = nx.to_edgelist(G)                                     
for e in EdgeListGraph:
    v1, v2, w = e
    print(v1, v2)

###### Graph to EdgeList ######
1 2
1 10
2 3
3 4
4 5
5 6
6 7
7 8
8 9
9 10


In [33]:
# 그래프를 인접 행렬(일반 행렬)로 저장
print("###### Graph to numpy array ######")
NumpyArrayGraph = nx.to_numpy_array(G)                                    
print(NumpyArrayGraph)


###### Graph to numpy array ######
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 1. 0.]]


In [34]:
# 그래프를 인접 행렬(희소 행렬)로 저장
print("###### Graph to Spicy sparse matrix ######")
SparseMatrixGraph = nx.to_scipy_sparse_matrix(G)                       
print(SparseMatrixGraph)

###### Graph to Spicy sparse matrix ######
  (0, 1)	1
  (0, 9)	1
  (1, 0)	1
  (1, 2)	1
  (2, 1)	1
  (2, 3)	1
  (3, 2)	1
  (3, 4)	1
  (4, 3)	1
  (4, 5)	1
  (5, 4)	1
  (5, 6)	1
  (6, 5)	1
  (6, 7)	1
  (7, 6)	1
  (7, 8)	1
  (8, 7)	1
  (8, 9)	1
  (9, 0)	1
  (9, 8)	1


In [37]:
len(G.nodes), G.nodes

(10, NodeView((1, 2, 3, 4, 5, 6, 7, 8, 9, 10)))

In [51]:
G.edges

EdgeView([(1, 10), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)])

In [68]:
adj_nodes = [k for k in G.adj[1]]
adj_nodes

[10, 2]

In [69]:
for k in adj_nodes:
    print(k)
    G.remove_edge(k, 1)

10
2


In [70]:
G.edges

EdgeView([(2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (9, 10)])

In [81]:
#-*- coding:utf-8 -*-
import os
import os.path as osp
import time
from collections import defaultdict
from typing import DefaultDict, Dict, Set, TextIO, Tuple, Union, List
import numpy as np
import sys
from abc import *
np.set_printoptions(threshold=sys.maxsize)

In [82]:
###################################################
#   Abstract Graph class                          #
#                                                 #
###################################################
class DiGraph(metaclass=ABCMeta):
    
    @abstractmethod
    def __str__(self):
        pass
    
    @abstractmethod
    def nodes(self) -> Set[int]:
        pass

    @abstractmethod
    def edges(self) -> List[Tuple[int, int]]:
        pass
    
    @abstractmethod
    def add_vertex(self, v: int) -> None:
        pass
    
    @abstractmethod
    def remove_vertex(self, v: int) -> None:
        pass

    @abstractmethod
    def add_edge(self, src: int, dst: int) -> None:
        pass

    @abstractmethod
    def remove_edge(self, src: int, dst: int) -> None:
        pass

    @abstractmethod
    def out_neighbor(self, v: int):
        pass

    @abstractmethod
    def out_degree(self, v: int) -> int:
        pass

    @abstractmethod
    def has_edge(self, src: int, dst: int) -> bool:
        pass


In [148]:
###################################################
#   Dictionary Array Graph                        #
#    - 정점       : self._nodes                   #             
#    - 나가는간선 : self._out_neighbor            #
#                                                 #
###################################################
class Graph_dict(DiGraph):

    def __init__(self) -> None:
        self._nodes = set()
        self._out_neighbor = defaultdict(set)

    def __str__(self):
        result = ""
        for v in self._nodes:
            neighbors = self._out_neighbor[v]
            if not neighbors:
                result = result + str(v) + " : empty\n"
            else : result = result + str(v) + " : " +  str(neighbors) + "\n"
        return result
    
    def nodes(self) -> Set[int]:
        return self._nodes

    def edges(self) -> List[Tuple[int, int]]:
        edges = []
        for v1 in self._nodes:
            neighbors = self._out_neighbor[v1]
            for v2 in neighbors:
                edges.append((v1, v2))
        return edges
        


    ################# Write your answer here #####################
    def add_vertex(self, v: int) -> None:
        return self._nodes.add(v)

    ################# Write your answer here #####################
    def remove_vertex(self, v: int) -> None:
        if len(self._nodes) == 0:
            return
        else:
            self._nodes.remove(v)
            adj_nodes = [node for node in self._out_neighbor[v]]
            for node in adj_nodes:
                self.remove_edge(v, node)

    def add_edge(self, src: int, dst: int) -> None:
        self.add_vertex(src)
        self.add_vertex(dst)
        self._out_neighbor[src].add(dst)

    def remove_edge(self, src: int, dst: int) -> None:
        neighbor = self.out_neighbor(src)
        if dst in neighbor:
            self._out_neighbor[src].remove(dst)

    ################# Write your answer here #####################
    def out_neighbor(self, v: int) -> Set[int]:
        return self._out_neighbor[v]
    
    ################# Write your answer here #####################
    def out_degree(self, v: int) -> int:
        return len(self._out_neighbor[v])
    
    def has_edge(self, src: int, dst: int) -> bool:
        return dst in self._out_neighbor[src]
    
    ################# Write your answer here #####################
    # HW 1-2
    def subgraph(self, vertices: List[int]):
        raise NotImplemented 


In [149]:
graph_dict = Graph_dict()

In [150]:
graph_dict.nodes()

set()

In [151]:
graph_dict.add_vertex(1)
graph_dict.add_vertex(3)

In [153]:
graph_dict.add_edge(1, 3)

In [154]:
graph_dict.add_edge(1, 5)

In [156]:
graph_dict.nodes()

{1, 3, 5}

In [157]:
graph_dict.out_neighbor(1)

{3, 5}

In [158]:
graph_dict.remove_vertex(1)

In [159]:
graph_dict.nodes()

{3, 5}

In [160]:
graph_dict.edges()

[]