In [2]:
import numpy as np

In [4]:
def sigmoid(x):
    s = 1/(1+np.exp(-x))
    return s

def relu(x):
    s = np.maximum(0,x)
    return s

In [5]:
def initialize_parameters(layer_dims):
    
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims) # number of layers in the network

    for l in range(1, L):
        parameters['W' + str(l)] = np.random.randn(layer_dims[l], layer_dims[l-1])*  np.sqrt(2 / layer_dims[l-1])
        parameters['b' + str(l)] = np.zeros((layer_dims[l], 1))
        
    return parameters

In [18]:
def forward_propagation(X, parameters):
    
    # retrieve parameters
    W1 = parameters["W1"]
    b1 = parameters["b1"]
    W2 = parameters["W2"]
    b2 = parameters["b2"]
    
    # LINEAR -> RELU -> LINEAR -> RELU -> LINEAR -> SIGMOID
    z1 = np.dot(W1, X) + b1
    a1 = relu(z1)
    z2 = np.dot(W2, a1) + b2
    a2 = sigmoid(z2)
    
    cache = (z1, a1, W1, b1, z2, a2, W2, b2)
    
    return a2, cache

In [24]:
def backward_propagation(X, Y, cache):
    
    m = X.shape[1]
    (z1, a1, W1, b1, z2, a2, W2, b2) = cache
    
    dz2 = 1/m * (a2 - Y) # 예측값 - 실제값
    dW2 = np.dot(dz2, a1.T)
    db2 = np.sum(dz2, axis = 1, keepdims = True)
    
    da1 = np.dot(W2.T, dz2)
    dz1 = np.multiply(da1, np.int64(a1 > 0))
    dW1 = np.dot(dz1, X.T)
    db1 = np.sum(dz1, axis = 1, keepdims = True)
    
    gradients = {"dz2": dz2, "dW2": dW2, "db2": db2,
                 "da1": da1, "dz1": dz1, "dW1": dW1, "db1": db1}
    
    return gradients

In [9]:
# GRADED FUNCTION: update_parameters_with_gd

def update_parameters_with_gd(parameters, grads, learning_rate):
    
    L = len(parameters) // 2 # number of layers in the neural networks

    # Update rule for each parameter
    for l in range(L):
        ### START CODE HERE ### (approx. 2 lines)
        parameters["W" + str(l+1)] = parameters["W" + str(l + 1)] - learning_rate * grads["dW" + str(l + 1)]
        parameters["b" + str(l+1)] = parameters["b" + str(l + 1)] - learning_rate * grads["db" + str(l + 1)]
        ### END CODE HERE ###
        
    return parameters

In [82]:
def compute_cost(a3, Y):
    
    logprobs = np.multiply(-np.log(a3),Y) + np.multiply(-np.log(1 - a3), 1 - Y)
    cost_total =  np.sum(logprobs)
    
    return cost_total

In [30]:
def model(X, Y, layers_dims, optimizer, learning_rate = 0.0007, mini_batch_size = 64, beta = 0.9,
          beta1 = 0.9, beta2 = 0.999,  epsilon = 1e-8, num_epochs = 10000, print_cost = True):
    
    L = len(layers_dims)             # number of layers in the neural networks
    costs = []                       # to keep track of the cost
    t = 0                            # initializing the counter required for Adam update
    seed = 10                        # For grading purposes, so that your "random" minibatches are the same as ours
    m = X.shape[1]                   # number of training examples
    
    # Initialize parameters
    parameters = initialize_parameters(layers_dims)
    print(parameters)
    for i in range(num_epochs):
        
        cost_total = 0
        
        a3, caches = forward_propagation(X, parameters)
        
        cost_total += compute_cost(a3, Y)
        
        grads = backward_propagation(X, Y, caches)
        
        parameters = update_parameters_with_gd(parameters, grads, learning_rate)
        
        cost_avg = cost_total / m
        
        if print_cost and i % 1000 == 0:
            print ("Cost after epoch %i: %f" %(i, cost_avg))
        if print_cost and i % 100 == 0:
            costs.append(cost_avg)
            
    return parameters

In [6]:
np.random.seed(1)
X = np.random.randn(3,2)
Y = np.array([1, 0])

print(X)

[[ 1.62434536 -0.61175641]
 [-0.52817175 -1.07296862]
 [ 0.86540763 -2.3015387 ]]


In [89]:
layers_dims = [X.shape[0], 2, 1]
parameters = model(X, Y, layers_dims, optimizer = "gd")

{'W1': array([[ 1.46040903,  0.3564088 ,  0.07878985],
       [-1.52153542, -0.22648652, -0.28965949]]), 'b1': array([[0.],
       [0.]]), 'W2': array([[-0.08274148, -0.62700068]]), 'b2': array([[0.]])}
Cost after epoch 0: 0.532389
Cost after epoch 1000: 0.294104
Cost after epoch 2000: 0.175846
Cost after epoch 3000: 0.113758
Cost after epoch 4000: 0.079260
Cost after epoch 5000: 0.058659
Cost after epoch 6000: 0.045488
Cost after epoch 7000: 0.036567
Cost after epoch 8000: 0.030232
Cost after epoch 9000: 0.025558


In [91]:
a3, caches = forward_propagation(X, parameters)

In [92]:
a3

array([[0.97330891, 0.01679874]])

In [93]:
caches

(array([[ 3.20077329, -1.74558583],
        [-2.90073463,  3.48458454]]),
 array([[3.20077329, 0.        ],
        [0.        , 3.48458454]]),
 array([[ 1.79061984,  0.24903753,  0.25471731],
        [-1.65011036, -0.451996  , -0.77338174]]),
 array([[0.20328855],
        [0.21017342]]),
 array([[ 3.59637161, -4.06951008]]),
 array([[0.97330891, 0.01679874]]),
 array([[ 1.05620203, -1.22976452]]),
 array([[0.21570836]]))

In [7]:
layers_dims = [X.shape[0], 2, 1]

In [8]:
parameters = initialize_parameters(layers_dims)

In [9]:
parameters

{'W1': array([[ 1.46040903,  0.3564088 ,  0.07878985],
        [-1.52153542, -0.22648652, -0.28965949]]),
 'b1': array([[0.],
        [0.]]),
 'W2': array([[-0.08274148, -0.62700068]]),
 'b2': array([[0.]])}

In [11]:
# retrieve parameters
W1 = parameters["W1"]
b1 = parameters["b1"]
W2 = parameters["W2"]
b2 = parameters["b2"]

# LINEAR -> RELU -> LINEAR -> RELU -> LINEAR -> SIGMOID
z1 = np.dot(W1, X) + b1
a1 = relu(z1)
z2 = np.dot(W2, a1) + b2
a2 = sigmoid(z2)

cache = (z1, a1, W1, b1, z2, a2, W2, b2)

In [16]:
W1

array([[ 1.46040903,  0.3564088 ,  0.07878985],
       [-1.52153542, -0.22648652, -0.28965949]])

In [18]:
X

array([[ 1.62434536, -0.61175641],
       [-0.52817175, -1.07296862],
       [ 0.86540763, -2.3015387 ]])

In [17]:
z1

array([[ 2.25214892, -1.45716795],
       [-2.60254876,  1.84048451]])

In [13]:
a1

array([[2.25214892, 0.        ],
       [0.        , 1.84048451]])

array([[ 2.25214892, -1.45716795],
       [-2.60254876,  1.84048451]])